###########################################################
#                Avorix Domain Controller                 #
###########################################################
#
# This is currently in development!
# I recommend to execute this script per command in
# a CLEAN RASPBIAN installation!
#
# The Avorix Domain Controller uses SAMBA, NTP, DHCPD to
# mimic Microsoft Active Directory Domain Services
# (MS ADDS) on Raspberry Pi's running Raspbian while
# keeping it's configuration on a USB-memory device.
#
# This allows us to manage computers, users, shares,
# and policies using the RSAT-tools.
#
# This script was built upon best practices and experiences.
# ~ Rik Heijmann

###########################################################
#                       Versions                          #
###########################################################
VERSION=0.5
# 0.5: First release: Installs a SAMBA, NTP, DHCP server in
#                     A Secure environment.

###########################################################
#                         To Do                           #
###########################################################
# - Make this script work with CentOS, ArchLinux and Ubuntu.
# - Integrate a GUI for configuration.
# - Integrate checks.
# - Find a way to make AUDITD to work.
# - Use PXE to deploy Windows.
# - Set the permissions on the "users"-share automaticly.


###########################################################
#                       Summary                           #
###########################################################
# 1. Settings.
# 2. Update the complete system.
# 3. Configure the USB to save important files.
# 4. (Optional) Install & Temporarely disable SELinux  
# 5. Install the main components.
# 6. Configure the timezone  
# 7. Configure the hosts file.
# 8. Change the hostname.
# 9. Configure a static IP-address.
# 10. (Optional) Configure SSH.
# 11. Configure the NTP-server.
# 12. Configure SAMBA.
# 13. (Optional) Configure the DHCP-server.
# 14. (Optional) Configure SELinux.
# 15. (Optional) Configure automatic security updates.


###########################################################
# 1.                   Settings                           #
###########################################################
# All these settings are important!
# Make sure that everything is setup correctly.

#Additional Modules
export DHCP=0 #Enable this only if you know that this is needed.
export SSH=0

#Security Functions
export FIREWALL=1 #RECOMMENDED! Enables the built-in firewall and adds support for the selected functions.
export SELINUX=1 #RECOMMENDED! Enables SELINUX (Will first start permissive and collect data. The next day that data will be used to create a policy)
export AUTOMATIC_SECURITY_UPDATES=1 #RECOMMENDED! Will daily check for security updates.

#Storage Settings
AUTO_CHECK_USB=1 
export USB=/media/usb1 #Will only work if AUTO_CHECK_USB is set to 0.

#Network Settings
export IP_ADDRESS=192.168.0.2
export SUBNETMASK_BITS=24

#Active Directory Settings
export FQDN=avorix.local #This is your domain name.
export NBIOS=AVORIX #This is the second level domain name capitalized.
export DCNAME=DC1
ADMINPWD=P@$$w0RD! #This is the password of the "Administrator"-account.

#Time Settings
export REGION=Europe
export TIMEZONE=Amsterdam
export NTPSERVER1=0.pool.ntp.org
export NTPSERVER2=1.pool.ntp.org
export NTPSERVER3=2.pool.ntp.org

#(Optional) DHCP Settings
export SUBNET=192.168.0.0
export SUBNETMASK=255.255.255.0
export BROADCASTADDRESS=192.168.0.255
export GATEWAY=192.168.0.1
export DNSSERVER1=$IP_ADDRESS
export DNSSERVER2=8.8.8.8
export NETBIOSSERVER=$IP_ADDRESS
export CLIENT_NTPSERVER1=$IP_ADDRESS
export CLIENT_NTPSERVER2=0.pool.ntp.org
export MAX_LEASE_TIME=1800
export FIRST_IP_ADDRESS=192.168.0.10
export LAST_IP_ADDRESS=192.168.0.200

#(Optional) SSH Settings
SSH_PORT=22
SSH_USER=Avorix #Future users have to be added to the "ssh"-group to use "ssh".
SSH_USER_PASSWORD=P@$$w0rd!
SSH_USER_SUDO=1 #Set to 1 to give this user permission to run administrator commands using "sudo".


###########################################################
# 2.          Update the complete system                  #
###########################################################
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y


###########################################################
# 3.    Configure the USB to save important files         #
###########################################################
sudo apt-get install ntfs-3g usbmount -y

#USBMount: Configuring.
sudo mv /etc/usbmount/usbmount.conf /etc/usbmount/usbmount.conf.original
sudo touch /etc/usbmount/usbmount.conf
sudo cat <<EOT >> /etc/usbmount/usbmount.conf
#Generated by the Avorix Domain Controller install script.
ENABLED=1
MOUNTPOINTS="/media/usb1 /media/usb2 /media/usb3
             /media/usb4 /media/usb5 /media/usb6 /media/usb7 /media/usb8"
			 
FILESYSTEMS="ntfs-3g vfat ext2 ext3 ext4 hfsplus"
MOUNTOPTIONS="sync,noexec,nodev,noatime,nodiratime"
FS_MOUNTOPTIONS=""
VERBOSE=no
EOT

#USBMount: Make sure that the USB-drive is mounted else copy the files to a temporary folder.
#It would be better if we listed the drives using mountusb.
if [ "$AUTO_CHECK_USB" -eq "1" ] && mount | grep /media/usb1 > /dev/null ; then
    export USB=/media/usb1
else
    export USB=/media/temp
fi

#Creating folders for the $USB
sudo mkdir -p $USB/General/Configuration $USB/General/Logs $USB/Kerberos/Configuration $USB/SAMBA/Configuration $USB/SAMBA/State $USB/SAMBA/Setup $USB/SAMBA/Cache $USB/SAMBA/Logs $USB/SAMBA/Sockets/ntp_signd $USB/NTPD/Configuration $USB/NTPD/Logs $USB/NTPD/Data

#Linking folder to folders on the USB.
sudo ln -sf $USB/SAMBA/State/ /var/lib/samba/
sudo ln -sf $USB/SAMBA/Setup/ /usr/share/samba/setup
sudo ln -sf $USB/SAMBA/Cache/ /var/cache/samba
sudo ln -sf $USB/SAMBA/Logs/ /var/log/samba

sock
###########################################################
# 4.(Optional)   Install & Temporarely disable SELinux    #
###########################################################
#Temporary disable SELinux, will be enabled the next day with exclusions for DNS, SAMBA, DHCP and DHCP.
if [ "$SELINUX" -eq "1" ]; then
sudo apt-get install selinux-basics selinux-policy-default -y
sudo selinux-activate
sudo mv /etc/selinux/config /etc/selinux/config.original
sudo touch /etc/selinux/config
sudo cat <<EOT >> /etc/selinux/config
# Generated by the Avorix Domain Controller install script $VERSION
# Generated on $(date)
#
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - SELinux is fully disabled.
SELINUX=permissive
# SELINUXTYPE= type of policy in use. Possible values are:
#       targeted - Only targeted network daemons are protected.
#       strict - Full SELinux protection.
SELINUXTYPE=strict

# SETLOCALDEFS= Check local definition changes
SETLOCALDEFS=0
EOT
fi


###########################################################
# 5.             Install the main components              #
###########################################################
if [ "$DHCP" -eq "1" ]; then
   sudo apt-get install isc-dhcp-server -y
fi

if [ "$FIREWALL" -eq "1" ]; then
   sudo apt-get firewalld -y
fi

if [ "$SSH" -eq "1" ]; then
   sudo apt-get openssh-server -y
fi

sudo apt-get install samba samba-windbind samba-vfs-modules ntp -y


###########################################################
# 6.                Configure the timezone                #
###########################################################
sudo timedatectl set-timezone $REGION/$TIMEZONE
sudo timedatectl


###########################################################
# 7.            Configure the hosts file                  #
###########################################################
sudo mv /etc/hosts /etc/hosts.original
sudo touch $USB/General/Configuration/hosts
sudo ln -sf $USB/General/Configuration/hosts /etc/hosts
sudo cat <<EOT >> $USB/General/Configuration/hosts
#Generated by the Avorix Domain Controller install script.
#Localhost
127.0.0.1     localhost localhost
::1           localhost ip6-localhost ip6-loopback

#Domain name
$IP_ADDRESS     $DCNAME.$FQDN     $DCNAME

#Might not be needed.
ff02::1       ip6-allnodes
ff02::2       ip6-allrouters
EOT


###########################################################
# 8.                 Change the hostname                  #
###########################################################
#Change the hostname and backup the original.
sudo mv /etc/hostname /etc/hostname.original
sudo touch $USB/General/Configuration/hostname
sudo ln -sf $USB/General/Configuration/hostname /etc/hostname
sudo cat <<EOT >> $USB/General/Configuration/hostname
$DCNAME.$FQDN
EOT

#Make the hostname for the current session active.
sudo hostname $DCNAME.$FQDN


###########################################################
# 9.         Configure a static IP-address                #
###########################################################
#Change the IP-address to static.
#First create a backup.
sudo mv /etc/dhcpcd.conf /etc/dhcpcd.conf.original
#Create an empty file.
sudo touch $USB/General/Configuration/dhcpcd.conf
#Link that file to the file that wil be used by DHCPCD.
sudo ln -sf $USB/General/Configuration/dhcpcd.conf /etc/dhcpcd.conf
#Fill that file with the text that starts at "#Generated" till "$DNSSERVER2". 
sudo cat <<EOT >> $USB/General/Configuration/dhcpcd.conf
# Generated by the Avorix Domain Controller install script $VERSION.
# Generated on $(date)
#
# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
hostname

# Use the hardware address of the interface for the Client ID.
clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
#duid

# Persist interface configuration when dhcpcd exits.
persistent

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
# Most distributions have NTP support.
option ntp_servers
# Respect the network MTU.
# Some interface drivers reset when changing the MTU so disabled by default.
#option interface_mtu

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate Stable Private IPv6 Addresses instead of hardware based ones
slaac private

# A hook script is provided to lookup the hostname if not set by the DHCP
# server, but it should not be run by default.
nohook lookup-hostname

interface eth0
static ip_address=$IP_ADDRESS/$SUBNETMASK_BITS
static routers=$GATEWAY
static domain_name_servers=$DNSSERVER1, $DNSSERVER2
EOT
sudo systemctl restart dhcpcd


###########################################################
# 10.(Optional)          Configure SSH                    #
###########################################################
#SSH allows us to remotely open a terminal shell.
#Within a terminal shell we are able to completely modify the system.
#But if you are only in to modifying Active Directory just install the RSAT-tools, you won't need SSH.
if [ "$SSH" -eq "1" && "$FIREWALL" -eq "1" ]; then
sudo firewall-cmd --permanent --zone=public --add-port=$SSH_PORT/tcp
fi

#If the SSH user needs SSH access, create the SSH group and the SSH user.
if [ "$SSH" -eq "1" && "$SSH_USER_SUDO" -eq "1" ]; then
sudo groupadd ssh
sudo useradd $SSH_USER -d /home/$SSH_USER -g ssh -g sudo -m -p $SSH_USER_PASSWORD
else
sudo groupadd ssh
sudo useradd $SSH_USER -d /home/$SSH_USER -g ssh -m -p $SSH_USER_PASSWORD
fi

if [ "$SSH" -eq "1" ]; then
   sudo mkdir -p $USB/SSH/Configuration
   sudo mv /etc/ssh/sshd_config /etc/ssh/sshd_config.orginal
   sudo touch /etc/ssh/sshd_config
   sudo ln -sf $USB/SSH/Configuration/sshd_config /etc/ssh/sshd_config
   sudo cat <<EOT >> $USB/SSH/Configuration/sshd_config
# Generated by the Avorix Domain Controller install script $VERSION
# Generated on $(date)
#
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Port $SSH_PORT
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

# The default requires explicit activation of protocol 1
Protocol 2

# HostKey for protocol version 1
#HostKey /etc/ssh/ssh_host_key
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Lifetime and size of ephemeral version 1 server key
#KeyRegenerationInterval 1h
#ServerKeyBits 1024

# Ciphers and keying
#RekeyLimit default none
Ciphers aes256-ctr,blowfish-cbc,aes256-cbc
MACs hmac-sha2-256,hmac-sha2-512,hmac-sha1

# Logging
# obsoletes QuietMode and FascistLogging
SyslogFacility AUTH
LogLevel VERBOSE

# Authentication:

LoginGraceTime 2m
PermitRootLogin no
StrictModes yes
MaxAuthTries 2
#MaxSessions 10

#RSAAuthentication yes
#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
RhostsRSAAuthentication no
# similar for protocol version 2
HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# RhostsRSAAuthentication and HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
PermitEmptyPasswords yes

# Change to no to disable s/key passwords
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
AllowTcpForwarding no
GatewayPorts no
X11Forwarding no
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no # pam does that
#PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
UsePrivilegeSeparation yes		# Default for new installations.
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
Banner /etc/issue.net

# override default of no subsystems
Subsystem	sftp	/usr/lib/ssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

AllowGroups ssh
EOT

sudo systemctl stop ssh
sudo systemctl start ssh
sudo systemctl enable ssh
fi


###########################################################
# 11.          Configure the NTP-server                   #
###########################################################
#If function FIREWALL is enabled then allow NTP to send and recieve over the network.
if [ "$FIREWALL" -eq "1" ]; then
sudo firewall-cmd --permanent --zone=public --add-port=123/udp
fi

sudo mv /etc/ntp.conf /etc/ntp.conf.original
sudo touch $USB/NTPD/Configuration/ntp.conf
sudo ln -sf $USB/NTPD/Configuration/ntp.conf /etc/ntp.conf
sudo cat <<EOT >> $USB/NTPD/Configuration/ntp.conf
# Generated by the Avorix Domain Controller install script $VERSION
# Generated on $(date)
#
# Local clock. Note that is not the "localhost" address!
server 127.127.1.0
fudge  127.127.1.0 stratum 10

# Where to retrieve the time from
server $NTPSERVER1     iburst prefer
server $NTPSERVER2     iburst prefer
server $NTPSERVER3     iburst prefer

driftfile       $USB/NTPD/Data/ntp.drift
logfile         $USB/NTPD/Logs
ntpsigndsocket  $USB/SAMBA/Sockets/ntp_signd/

# Access control
# Default restriction: Allow clients only to query the time
restrict default kod nomodify notrap nopeer mssntp

# No restrictions for "localhost"
restrict 127.0.0.1

# Enable the time sources to only provide time to this host
restrict $NTPSERVER1   mask 255.255.255.255    nomodify notrap nopeer noquery
restrict $NTPSERVER2   mask 255.255.255.255    nomodify notrap nopeer noquery
restrict $NTPSERVER3   mask 255.255.255.255    nomodify notrap nopeer noquery
EOT
sudo systemctl stop ntp
sudo systemctl start ntp
sudo systemctl enable ntp


###########################################################
# 12.                Configure Samba                      #
###########################################################
if [ "$FIREWALL" -eq "1" ]; then
#SAMBA: DNS
sudo firewall-cmd --permanent --zone=public --add-port=53/tcp
sudo firewall-cmd --permanent --zone=public --add-port=53/udp

#SAMBA: Kerberos
sudo firewall-cmd --permanent --zone=public --add-port=88/tcp
sudo firewall-cmd --permanent --zone=public --add-port=88/udp

#SAMBA: End Point Mapper (DCE\RPC Locator Service)
sudo firewall-cmd --permanent --zone=public --add-port=135/tcp

#SAMBA: NetBIOS Name Service
sudo firewall-cmd --permanent --zone=public --add-port=137/udp

#SAMBA: NetBIOS Datagram
sudo firewall-cmd --permanent --zone=public --add-port=138/udp

#SAMBA: NetBIOS Session
sudo firewall-cmd --permanent --zone=public --add-port=139/udp

#SAMBA: LDAP
sudo firewall-cmd --permanent --zone=public --add-port=389/tcp
sudo firewall-cmd --permanent --zone=public --add-port=389/udp
#sudo firewall-cmd --permanent --zone=public --add-port=636/tcp #For TLS-encryption

#SAMBA: SMB over TCP
sudo firewall-cmd --permanent --zone=public --add-port=445/tcp

#SAMBA: Kerberos kpasswd
sudo firewall-cmd --permanent --zone=public --add-port=464/tcp
sudo firewall-cmd --permanent --zone=public --add-port=464/udp

#SAMBA: Global Catalog
sudo firewall-cmd --permanent --zone=public --add-port=3268/tcp
#firewall-cmd --permanent --zone=public --add-port=3269/tcp #For TLS-encryption

#SAMBA: Dynamic RPC Ports
sudo firewall-cmd --permanent --add-port=1024-5000/tcp
sudo firewall-cmd --permanent --add-port=1024-5000/udp
fi

#Linking the configs to the USB and creating the DC.
sudo mv /etc/samba/smb.conf /etc/samba/smb.conf.original
sudo samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm=$FQDN --domain=$NBIOS --host-name=$DCNAME --adminpass=$ADMINPWD --host-ip=$IP_ADDRESS

sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.after_provision
sudo mv /etc/samba/smb.conf $USB/SAMBA/Configuration/smb.conf
sudo ln -sf $USB/SAMBA/Configuration/smb.conf /etc/samba/smb.conf

sudo cp /var/lib/samba/private/krb5.conf $USB/Kerberos/Configuration/krb5.conf
sudo ln -sf $USB/Kerberos/krb5.conf /etc/krb5.conf

sudo mkdir -p &USB/SAMBA/Shares/Users
sudo cat <<EOT >> $USB/SAMBA/Configuration/smb.conf

[users]
       path = &USB/SAMBA/Shares/Users
       read only = no
EOT

sudo systemctl stop smbd
sudo systemctl start smbd
sudo systemctl enable smbd

sudo systemctl stop nmbd
sudo systemctl start nmbd
sudo systemctl enable nmbd

sudo systemctl stop samba-ad-dc
sudo systemctl start samba-ad-dc
sudo systemctl enable samba-ad-dc


###########################################################
# 13.(Optional)    Configure the DHCP server              #
###########################################################
#In some situations and environments you do not want to have an additional DHCP-server.
#As there can only be 1 DHCP-server in a network. Having multiple will cause network failure.
#But to make the Domain Controller reachable you will need to let the DHCP-server instruct the devices on the network
#to use the DNS, NTP and the NetBIOS server of the Domain Controller.
if [ "$DHCP" -eq "1" && "$FIREWALL" -eq "1"]; then
sudo firewall-cmd --permanent --zone=public --add-port=67/udp
fi

if [ "$DHCP" -eq "1" ]; then
cat <<EOT >> /etc/dhcpd.conf
subnet $SUBNET netmask $SUBNETMASK {
  option subnet-mask $SUBNETMASK;
  option broadcast-address $BROADCASTADDRESS;
  option time-offset 0;
  option routers $GATEWAY;
  option domain-name "$FQDN";
  option domain-name-servers $DNSSERVER1, $DNSSERVER2;
  option netbios-name-servers $NETBIOSSERVER;
  option ntp-servers $CLIENT_NTPSERVER1, $CLIENT_NTPSERVER2;
  pool {
    max-lease-time $MAX_LEASE_TIME; # 30 minutes
    range $FIRST_IP_ADDRESS $LAST_IP_ADDRESS;
  }
}
EOT

sudo systemctl stop isc-dhcp-server
sudo systemctl start isc-dhcp-server
sudo systemctl enable isc-dhcp-server
fi


###########################################################
# 14.(Optional)          Configure SELinux                #
###########################################################
#SELinux is a security module for the Linux kernel.
#It allows us to create security policy for each process.
#The policies include: Allowing files to be accessed, Allowing services to be run.

#Creates a script that wil check the next day which permissions NTP, SAMBA and DHCP need.
if [ "$SELINUX" -eq "1" ]; then
sudo apt-get install selinux-basic selinux-policy-defaults
sudo mkdir -p $USB/SELinux/Rules 
sudo touch /etc/cron.daily/Configure-SELinux.sh
sudo cat <<EOT >> /etc/cron.daily/Configure-SELinux.sh
# Generated by the Avorix Domain Controller install script $VERSION
# Generated on $(date)
#
sudo grep smb /var/log/audit/audit.log | sudo audit2allow -M $USB/Kerberos/Configuration/smb
sudo grep ntp /var/log/audit/audit.log | sudo audit2allow -M $USB/Kerberos/Configuration/ntp
sudo grep dhcp /var/log/audit/audit.log | sudo audit2allow -M $USB/Kerberos/Configuration/dhcp
sudo semodule -i $USB/Kerberos/Configuration/smb
sudo semodule -i $USB/Kerberos/Configuration/ntp 
sudo semodule -i $USB/Kerberos/Configuration/dhcp
sudo mv -Rf /etc/selinux/config.replacer /etc/selinux/config
sudo rm -Rf /etc/cron.daily/Configure-SELinux.sh
EOT

#This file will be replaced with the original /etc/selinux/config once the above script is ran.
sudo touch /etc/selinux/config.replacer
sudo cat <<EOT >> /etc/selinux/config.replacer
# Generated by the Avorix Domain Controller install script $VERSION
# Generated on $(date)
#
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - SELinux is fully disabled.
SELINUX=enforced
# SELINUXTYPE= type of policy in use. Possible values are:
#       targeted - Only targeted network daemons are protected.
#       strict - Full SELinux protection.
SELINUXTYPE=strict

# SETLOCALDEFS= Check local definition changes
SETLOCALDEFS=0
EOT
fi


###########################################################
# 15.(Optional)  Configure automatic security updates     #
###########################################################
if [ "$AUTOMATIC_SECURITY_UPDATES" -eq "1" ]; then
#Check daily for updates and install the security updates.
sudo cat <<EOT >> /etc/cron.daily/Install-Security-Updates
# Generated by the Avorix Domain Controller install script $VERSION
# Generated on $(date)
#
echo "**************" >> $USB/General/Logs/Security-Updates.log
date >> $USB/General/Logs/Security-Updates.log
aptitude update >> $USB/General/Logs/Security-Updates.log
aptitude safe-upgrade -o Aptitude::Delete-Unused=false --assume-yes --target-release `lsb_release -cs`-security >> $USB/General/Logs/Security-Updates.log
echo "Security updates (if any) installed"
EOT
fi
reboot
